/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordersystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ThinkPad
 */
public class ChangePassword_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword_JFrame
     */
    public ChangePassword_JFrame() {
        initComponents();
        this.userNameTabel.setText(Customer.userName);
        JLabel jb=new JLabel(new ImageIcon("src/ordersystem/orderPicture.jpg"));
        jb.setBounds(this.getX(),this.getY(),this.getWidth(),this.getHeight());
        this.add(jb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameTabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        oldPasswordText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        newPasswordText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        reNewPasswordText = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("修 改 密 码");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("用户名");

        userNameTabel.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        userNameTabel.setToolTipText("这里显示当前用户名");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("填写以下信息进行密码修改：");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("原密码");

        oldPasswordText.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        oldPasswordText.setToolTipText("请输入原密码");

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("新密码");

        newPasswordText.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        newPasswordText.setToolTipText("请输入新密码");

        jLabel7.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel7.setText("确定密码");

        reNewPasswordText.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        reNewPasswordText.setToolTipText("请再次填写新密码");

        okButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        okButton.setText("确定");
        okButton.setToolTipText("点击这里确定修改");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        cancelButton.setText("取消");
        cancelButton.setToolTipText("点击这里重新填写");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        returnButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        returnButton.setText("返回");
        returnButton.setToolTipText("点击这里放弃修改并返回菜单界面");
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(okButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(returnButton))
                            .addComponent(oldPasswordText)
                            .addComponent(newPasswordText)
                            .addComponent(reNewPasswordText)
                            .addComponent(userNameTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(userNameTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(oldPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPasswordText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(reNewPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(returnButton)
                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okButtonActionPerformed

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        // TODO add your handling code here:
        Connection conn = null;
        Statement stat = null;
        boolean flag = true;
        try {
            String url;
            String userName = this.userNameTabel.getText();
            String password = this.oldPasswordText.getText();
            Class.forName("com.hxtt.sql.access.AccessDriver").newInstance();
            url = "jdbc:Access:///src/ordersystem/UserMessage.accdb";
            conn = DriverManager.getConnection(url);
            stat = conn.createStatement();
            String sql = "select * from userMessage where userName=\'" + userName + "\' ";
            ResultSet rs = stat.executeQuery(sql);
            rs.next();
            if (Customer.password.equals(password)) {
                if (this.newPasswordText.getText().equals("") || this.newPasswordText.getText().length() < 6) {
                    JOptionPane.showMessageDialog(null, "密码必须为6位及以上字符或数字！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                    flag = false;
                } else {
                    boolean judgePassword = true;
                    for (int i = 0; i < this.newPasswordText.getText().length(); i++) {
                        char temp = this.newPasswordText.getText().charAt(i);
                        if (temp < '0' || temp > '9') {
                            judgePassword = false;
                        }
                    }
                    if (judgePassword) {
                        JOptionPane.showMessageDialog(null, "密码中必须包含至少一个字符！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                        flag = false;
                    }
                }
                if (!this.newPasswordText.getText().equals(this.reNewPasswordText.getText())) {
                    JOptionPane.showMessageDialog(null, "两次输入的密码不相同！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                    flag = false;
                }
                if (flag) {
                    sql = "update userMessage set password=\'" + this.newPasswordText.getText() + "\' where userName=\'" + userName + "\'";
                    stat.executeUpdate(sql);//执行相应命令
                    Customer cm = new Customer();
                    cm.setPassword(password);
                    JOptionPane.showMessageDialog(null, "密码修改成功！返回菜单界面！", "温馨提示", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    new Menu_JFrame().setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "密码输入错误！", "温馨提示", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (stat != null) {
                    stat.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            }
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_okButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        this.oldPasswordText.setText(null);
        this.newPasswordText.setText(null);
        this.reNewPasswordText.setText(null);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu_JFrame().setVisible(true);
    }//GEN-LAST:event_returnButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main4(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField newPasswordText;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField oldPasswordText;
    private javax.swing.JTextField reNewPasswordText;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel userNameTabel;
    // End of variables declaration//GEN-END:variables
}
