/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordersystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ThinkPad
 */
public class ForgotPassword_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword_JFrame
     */
    public ForgotPassword_JFrame() {
        initComponents();
        JLabel jb=new JLabel(new ImageIcon("src/ordersystem/orderPicture.jpg"));
        jb.setBounds(this.getX(),this.getY(),this.getWidth(),this.getHeight());
        this.add(jb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phoneNumText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TipQuestionCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        TipAnswerText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        newPasswordText = new javax.swing.JTextField();
        reNewPasswordText = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("找 回 密 码");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("用户名");
        jLabel2.setToolTipText("");

        userNameText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        userNameText.setToolTipText("输入要找回的用户名");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("手机号");
        jLabel3.setToolTipText("");

        phoneNumText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        phoneNumText.setToolTipText("请输入注册时填写的手机号");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("请填写以下信息进行密码找回：");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("密码提示问题");

        TipQuestionCombo.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        TipQuestionCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "我叫什么名字？", "我住在哪里？", "我在哪里上学？", "我老家在哪里？" }));
        TipQuestionCombo.setToolTipText("请选择注册时对应的问题");

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("密码提示回答");

        TipAnswerText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        TipAnswerText.setToolTipText("请填写注册时对应的回答");

        jLabel7.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel7.setText("新密码");

        jLabel8.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel8.setText("确定密码");

        newPasswordText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        newPasswordText.setToolTipText("设置新的密码");

        reNewPasswordText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        reNewPasswordText.setToolTipText("请再次填写密码进行确定");

        okButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        okButton.setText("确定");
        okButton.setToolTipText("点击这里确定找回");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        cancelButton.setText("取消");
        cancelButton.setToolTipText("点击这里重新填写信息");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        returnButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        returnButton.setText("返回");
        returnButton.setToolTipText("取消找回并返回登陆界面");
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addGap(54, 54, 54)
                        .addComponent(cancelButton))
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TipQuestionCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(returnButton)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TipAnswerText, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(newPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(reNewPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(81, 81, 81)
                            .addComponent(phoneNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(81, 81, 81)
                            .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userNameText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phoneNumText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TipQuestionCombo)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipAnswerText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(newPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(reNewPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton)
                    .addComponent(returnButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        // TODO add your handling code here:
        boolean flag = true;
        Connection conn = null;
        Statement stat = null;
        try {
            String url;
            String userName = this.userNameText.getText();
            Class.forName("com.hxtt.sql.access.AccessDriver").newInstance();
            url = "jdbc:Access:///src/ordersystem/UserMessage.accdb";
            conn = DriverManager.getConnection(url);
            stat = conn.createStatement();
            String sql = "select * from userMessage where userName=\'" + userName + "\' ";
            ResultSet rs = stat.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "用户名不存在！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                flag = false;
            } else {
                if (!rs.getString(4).equals(this.phoneNumText.getText())) {
                    JOptionPane.showMessageDialog(null, "电话号码输入错误！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                    flag = false;
                }
                if (!rs.getString(5).equals(this.TipQuestionCombo.getSelectedItem().toString())) {
                    JOptionPane.showMessageDialog(null, "密码提示问题选择错误！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                    flag = false;
                }
                if (!rs.getString(6).equals(this.TipAnswerText.getText())) {
                    JOptionPane.showMessageDialog(null, "密码提示回答输入错误！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                    flag = false;
                }
                if (this.newPasswordText.getText().equals("") || this.newPasswordText.getText().length() < 6) {
                    JOptionPane.showMessageDialog(null, "密码必须为6位及以上字符或数字！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                    flag = false;
                } else {
                    boolean judgePassword = true;
                    for (int i = 0; i < this.newPasswordText.getText().length(); i++) {
                        char temp = this.newPasswordText.getText().charAt(i);
                        if (temp < '0' || temp > '9') {
                            judgePassword = false;
                        }
                    }
                    if (judgePassword) {
                        JOptionPane.showMessageDialog(null, "密码中必须包含至少一个字符！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                        flag = false;
                    }
                }
                if (!this.newPasswordText.getText().equals(this.reNewPasswordText.getText())) {
                    JOptionPane.showMessageDialog(null, "两次输入的密码不相同！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                    flag = false;
                }
            }
            if (flag) {
                sql = "update userMessage set password=\'" + this.newPasswordText.getText() + "\' where userName=\'" + userName + "\'";
                stat.executeUpdate(sql);//执行相应命令
                JOptionPane.showMessageDialog(null, "密码找回成功！返回登陆界面！", "温馨提示", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new Login_JFrame().setVisible(true);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (stat != null) {
                    stat.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            }
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_okButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        this.userNameText.setText(null);
        this.phoneNumText.setText(null);
        this.TipAnswerText.setText(null);
        this.newPasswordText.setText(null);
        this.reNewPasswordText.setText(null);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login_JFrame().setVisible(true);
    }//GEN-LAST:event_returnButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main3(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TipAnswerText;
    private javax.swing.JComboBox TipQuestionCombo;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField newPasswordText;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField phoneNumText;
    private javax.swing.JTextField reNewPasswordText;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables
}
