/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordersystem;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.Date;

/**
 *
 * @author ThinkPad
 */
public class Menu_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form Menu_JFrame
     */
    public Menu_JFrame() {
        initComponents();
        this.userNameLabel.setText(Customer.userName);
        JLabel jb = new JLabel(new ImageIcon("src/ordersystem/orderPicture.jpg"));
        jb.setBounds(this.menuPanel.getX(), this.menuPanel.getY(), this.menuPanel.getWidth(), this.menuPanel.getHeight());
        this.menuPanel.add(jb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();
        purchasedButton = new javax.swing.JButton();
        settlementButton = new javax.swing.JButton();
        specialtyButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pictureShowLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        changePasswordButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("菜 品 菜 单");

        menuTable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "菜品名称", "菜品价格", "菜品简介", "人气销量"
            }
        ));
        menuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(menuTable);

        updateButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateButton.setText("更新");
        updateButton.setToolTipText("更新菜品菜单");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });

        purchasedButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        purchasedButton.setText("点餐");
        purchasedButton.setToolTipText("点击加入点餐列表");
        purchasedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchasedButtonMouseClicked(evt);
            }
        });

        settlementButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        settlementButton.setText("下单");
        settlementButton.setToolTipText("下单并选择座位");
        settlementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settlementButtonMouseClicked(evt);
            }
        });

        specialtyButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        specialtyButton.setText("特色菜");
        specialtyButton.setToolTipText("点击查看特色菜");
        specialtyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                specialtyButtonMouseClicked(evt);
            }
        });

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "菜品名称", "菜品单价", "加购数量", "菜品总价"
            }
        ));
        jScrollPane3.setViewportView(orderTable);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("点餐信息");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("欢迎！");

        userNameLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        userNameLabel.setText("null");

        changePasswordButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        changePasswordButton.setText("修改密码");
        changePasswordButton.setToolTipText("点击这里修改密码");
        changePasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswordButtonMouseClicked(evt);
            }
        });

        orderButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        orderButton.setText("订单");
        orderButton.setToolTipText("点击这里查看订单");
        orderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderButtonMouseClicked(evt);
            }
        });

        returnButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        returnButton.setText("退出登录");
        returnButton.setToolTipText("点击这里返回登陆界面");
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(0, 299, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1)))
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pictureShowLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(changePasswordButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(returnButton))
                                    .addGroup(menuPanelLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(settlementButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(orderButton)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(menuPanelLayout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(purchasedButton))
                                    .addGroup(menuPanelLayout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(specialtyButton)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(updateButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changePasswordButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pictureShowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(specialtyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(purchasedButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(settlementButton)
                            .addComponent(orderButton)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePasswordButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ChangePassword_JFrame().setVisible(true);
    }//GEN-LAST:event_changePasswordButtonMouseClicked

    private void specialtyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specialtyButtonMouseClicked
        // TODO add your handling code here:
        TableModel tm = this.menuTable.getModel();
        DefaultTableModel dtm = (DefaultTableModel) tm;
        Connection conn = null;
        Statement stat = null;
        try {
            int row = dtm.getRowCount();
            if (row > 0) {
                int dish[] = new int[row];
                for (int i = 0; i < row; i++) {
                    dish[i] = Integer.valueOf((String) dtm.getValueAt(i, 3));
                }
                QuickSort qs = new QuickSort();
                dish = qs.quickSort(dish, 0, row - 1);
                String url, sql;
                ResultSet rs = null;
                Class.forName("com.hxtt.sql.access.AccessDriver").newInstance();
                url = "jdbc:Access:///src/ordersystem/MenuMessage.accdb";
                conn = DriverManager.getConnection(url);
                stat = conn.createStatement();
                for (int i = 0; i < row; i++) {
                    dtm.removeRow(0);
                }
                for (int i = 0; i < row; i++) {
                    sql = "select * from menuMessage where dishCount=" + dish[i] + "";
                    rs = stat.executeQuery(sql);
                    rs.next();
                    dtm.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
                }
                rs.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (stat != null) {
                    stat.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            }
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_specialtyButtonMouseClicked

    private void settlementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settlementButtonMouseClicked
        // TODO add your handling code here:
        TableModel tm = this.orderTable.getModel();
        DefaultTableModel dtm = (DefaultTableModel) tm;
        Connection conn = null;
        Statement stat = null;
        try {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String orderTime = df.format(new Date());
            Customer cm = new Customer();
            cm.setOrderTime(orderTime);
            int count = this.orderTable.getRowCount();
            if (count >= 1) {
                String url, sql;
                Object[] possibleValues = {"01", "02", "03", "04", "05"};
                String seat = (String) JOptionPane.showInputDialog(null, "请选择座位：\n", "下单", JOptionPane.INFORMATION_MESSAGE, null, possibleValues, null);
                if (seat != null) {
                    Class.forName("com.hxtt.sql.access.AccessDriver").newInstance();
                    url = "jdbc:Access:///src/ordersystem/OrderMessage.accdb";
                    conn = DriverManager.getConnection(url);
                    stat = conn.createStatement();
                    for (int i = 0; i < count; i++) {
                        sql = "insert into orderMessage (userName,dishName,dishPrice,orderCount,totalPrice,orderTime,orderSeat) values (\'"
                                + Customer.userName + "\',\'" + this.orderTable.getValueAt(i, 0).toString() + "\',\'"
                                + this.orderTable.getValueAt(i, 1).toString() + "\',\'" + this.orderTable.getValueAt(i, 2).toString() + "\',\'"
                                + this.orderTable.getValueAt(i, 3).toString() + "\',\'" + orderTime + "\',\'" + seat + "\')";
                        stat.executeUpdate(sql);
                    }
                    url = "jdbc:Access:///src/ordersystem/MenuMessage.accdb";
                    conn = DriverManager.getConnection(url);
                    stat = conn.createStatement();
                    String temp;
                    ResultSet rs = null;
                    for (int i = 0; i < count; i++) {
                        temp = "select *from menuMessage where dishName=\'" + this.orderTable.getValueAt(i, 0) + "\'";
                        rs = stat.executeQuery(temp);
                        rs.next();
                        int dishCount = Integer.valueOf(rs.getString(5)) + Integer.valueOf(this.orderTable.getValueAt(i, 2).toString());
                        sql = "update menuMessage set dishCount=\'" + dishCount + "\' where dishName=\'" + this.orderTable.getValueAt(i, 0).toString() + "\'";
                        stat.executeUpdate(sql);
                    }
                    rs.close();
                    for (int i = 0; i < count; i++) {
                        dtm.removeRow(0);
                    }
                    JOptionPane.showMessageDialog(null, "下单完成！点击订单进行查看！", "温馨提示", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (stat != null) {
                    stat.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            }
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_settlementButtonMouseClicked

    private void purchasedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasedButtonMouseClicked
        // TODO add your handling code here:
        TableModel tm = this.orderTable.getModel();
        DefaultTableModel dtm = (DefaultTableModel) tm;
        try {
            if (this.menuTable.getSelectedRowCount() == 1) {
                String dishCountTemp = JOptionPane.showInputDialog(null, "请选择点餐数量：\n", "点餐", JOptionPane.PLAIN_MESSAGE);
                if (!dishCountTemp.equals("")) {
                    int dishCount = Integer.valueOf(dishCountTemp);
                    int row = this.menuTable.getSelectedRow();
                    int total = Integer.valueOf(this.menuTable.getValueAt(row, 1).toString()) * dishCount;
                    dtm.addRow(new Object[]{this.menuTable.getValueAt(row, 0), this.menuTable.getValueAt(row, 1), dishCount, total});
                }
            } else {
                JOptionPane.showMessageDialog(null, "请先选择一种菜品！", "温馨提示", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "点餐已取消！", "温馨提示", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_purchasedButtonMouseClicked

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        // TODO add your handling code here:
        TableModel tm = this.menuTable.getModel();
        DefaultTableModel dtm = (DefaultTableModel) tm;
        Connection conn = null;
        Statement stat = null;
        try {
            String url;
            Class.forName("com.hxtt.sql.access.AccessDriver").newInstance();
            url = "jdbc:Access:///src/ordersystem/MenuMessage.accdb";
            conn = DriverManager.getConnection(url);
            stat = conn.createStatement();
            String sql = "select * from menuMessage";
            ResultSet rs = stat.executeQuery(sql);
            int count = dtm.getRowCount();
            for (int i = 0; i < count; i++) {
                dtm.removeRow(0);
            }
            while (rs.next()) {
                dtm.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (stat != null) {
                    stat.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            }
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void menuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTableMouseClicked
        // TODO add your handling code here:
        TableModel tm = this.menuTable.getModel();
        DefaultTableModel dtm = (DefaultTableModel) tm;
        Connection conn = null;
        Statement stat = null;
        try {
            String url;
            String dishName = dtm.getValueAt(this.menuTable.getSelectedRow(), 0).toString();
            Class.forName("com.hxtt.sql.access.AccessDriver").newInstance();
            url = "jdbc:Access:///src/ordersystem/MenuMessage.accdb";
            conn = DriverManager.getConnection(url);
            stat = conn.createStatement();
            String sql = "select * from menuMessage where dishName=\'" + dishName + "\'";
            ResultSet rs = stat.executeQuery(sql);
            rs.next();
            String Imagename = "src/ordersystem/dishPicture/" + rs.getString(2) + ".jpg";
            ImageIcon image = new ImageIcon(Imagename);
            int width = this.pictureShowLabel.getWidth();
            int height = this.pictureShowLabel.getHeight();
            Image img = image.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT);
            this.pictureShowLabel.setIcon(new ImageIcon(img));
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (stat != null) {
                    stat.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            }
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_menuTableMouseClicked

    private void orderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Order_JFrame().setVisible(true);
    }//GEN-LAST:event_orderButtonMouseClicked

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login_JFrame().setVisible(true);
    }//GEN-LAST:event_returnButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main2(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTable menuTable;
    private javax.swing.JButton orderButton;
    private javax.swing.JTable orderTable;
    private javax.swing.JLabel pictureShowLabel;
    private javax.swing.JButton purchasedButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton settlementButton;
    private javax.swing.JButton specialtyButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
