/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordersystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ThinkPad
 */
public class Register_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form Register_JFrame
     */
    public Register_JFrame() {
        initComponents();
        JLabel jb=new JLabel(new ImageIcon("src/ordersystem/orderPicture.jpg"));
        jb.setBounds(this.getX(),this.getY(),this.getWidth(),this.getHeight());
        this.add(jb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phoneNumText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TipQuestionCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        TipAnswerText = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("注 册 界 面");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("用户名");

        userNameText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        userNameText.setToolTipText("设置新的用户名");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("密  码");

        passwordText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        passwordText.setToolTipText("设置新的密码");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("电话号码");

        phoneNumText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        phoneNumText.setToolTipText("设置电话号码");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("密码提示问题");

        TipQuestionCombo.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        TipQuestionCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "我叫什么名字？", "我住在哪里？", "我在哪里上学？", "我老家在哪里？" }));

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("密码提示回答");

        TipAnswerText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        TipAnswerText.setToolTipText("设置密码提示回答");

        registerButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        registerButton.setText("注册");
        registerButton.setToolTipText("点击这里进行注册");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        cancelButton.setText("取消");
        cancelButton.setToolTipText("重新填写注册信息");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("请填写以下信息进行注册：");

        returnButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        returnButton.setText("返回");
        returnButton.setToolTipText("取消注册并返回登录界面");
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                .addComponent(passwordText)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(phoneNumText))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(registerButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                            .addComponent(cancelButton)
                            .addGap(53, 53, 53)
                            .addComponent(returnButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TipQuestionCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TipAnswerText)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userNameText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phoneNumText))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TipQuestionCombo)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(TipAnswerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(cancelButton)
                    .addComponent(returnButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:
        char temp;
        boolean flag = true;
        if (this.userNameText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "用户名不能为空！", "温馨提示", JOptionPane.WARNING_MESSAGE);
            flag = false;
        } else {
            Connection conn = null;
            Statement stat = null;
            try {
                String url;
                Class.forName("com.hxtt.sql.access.AccessDriver").newInstance();
                url = "jdbc:Access:///src/ordersystem/UserMessage.accdb";
                conn = DriverManager.getConnection(url);
                stat = conn.createStatement();
                String searchName = "select*from userMessage where userName=\'" + this.userNameText.getText() + "\'";
                ResultSet rs = stat.executeQuery(searchName);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "该用户名已存在！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                    flag = false;
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    if (stat != null) {
                        stat.close();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
                }
                try {
                    if (conn != null) {
                        conn.close();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        if (this.passwordText.getText().equals("") || this.passwordText.getText().length() < 6) {
            JOptionPane.showMessageDialog(null, "密码必须为6位及以上字符或数字！", "温馨提示", JOptionPane.WARNING_MESSAGE);
            flag = false;
        } else {
            boolean judgePassword = true;
            for (int i = 0; i < this.passwordText.getText().length(); i++) {
                temp = this.passwordText.getText().charAt(i);
                if (temp < '0' || temp > '9') {
                    judgePassword = false;
                }
            }
            if (judgePassword) {
                JOptionPane.showMessageDialog(null, "密码中必须包含至少一个字符！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                flag = false;
            }
        }
        if (this.phoneNumText.getText().equals("") || this.phoneNumText.getText().length() != 11) {
            JOptionPane.showMessageDialog(null, "电话号码不能为空,且必须为11位数字！", "温馨提示", JOptionPane.WARNING_MESSAGE);
            flag = false;
        } else {
            boolean judgePhoneNum = true;
            String firstNum = this.phoneNumText.getText().substring(0, 3);
            if (firstNum.equals("139") || firstNum.equals("138") || firstNum.equals("137") || firstNum.equals("186") || firstNum.equals("153")) {
                for (int i = 3; i < this.phoneNumText.getText().length(); i++) {
                    temp = this.phoneNumText.getText().charAt(i);
                    if (temp < '0' || temp > '9') {
                        JOptionPane.showMessageDialog(null, "电话号码中不能包含除数字外的其它字符！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                        flag = false;
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "电话号码开头必须是139、138、137、186或153！", "温馨提示", JOptionPane.WARNING_MESSAGE);
                flag = false;
            }
        }
        if (this.TipAnswerText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "密码提示回答不能为空！", "温馨提示", JOptionPane.WARNING_MESSAGE);
            flag = false;
        }
        if (flag) {
            Connection conn = null;
            Statement stat = null;
            try {
                String url;
                Class.forName("com.hxtt.sql.access.AccessDriver").newInstance();
                url = "jdbc:Access:///src/ordersystem/UserMessage.accdb";
                conn = DriverManager.getConnection(url);
                stat = conn.createStatement();
                String sql = "insert into userMessage (userName,password,phoneNum,TipQuestion,TipAnswer) values (\'"
                        + this.userNameText.getText() + "\',\'" + this.passwordText.getText() + "\',\'" + this.phoneNumText.getText() + "\',\'"
                        + this.TipQuestionCombo.getSelectedItem() + "\',\'" + this.TipAnswerText.getText() + "\')";
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "注册成功！返回登陆界面！", "温馨提示", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new Login_JFrame().setVisible(true);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    if (stat != null) {
                        stat.close();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
                }
                try {
                    if (conn != null) {
                        conn.close();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex.getStackTrace(), "错误", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_registerButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        this.userNameText.setText(null);
        this.passwordText.setText(null);
        this.phoneNumText.setText(null);
        this.TipAnswerText.setText(null);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login_JFrame().setVisible(true);
    }//GEN-LAST:event_returnButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TipAnswerText;
    private javax.swing.JComboBox TipQuestionCombo;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField passwordText;
    private javax.swing.JTextField phoneNumText;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables
}
